services:
    app:
        build:
            context: .
            args:
                NEW_UID: ${NEW_UID:-1000}
                NEW_GID: ${NEW_GID:-1000}
        volumes:
            - ./:/src
        ports:
            - 8509:8509
        networks:
            - zmodules

    postgres:
        image: postgres:14
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - 5409:5432
        networks:
            - zmodules

networks:
  zmodules:
    driver: bridge
    name: zmodules
