[tool.poetry]
name = "mcsd-consumer"
version = "0.1.0"
description = ""
license = "EUPL-1.2"
authors = ["Ministerie van Volksgezondheid, Welzijn en Sport"]
repository = "https://github.com/minvws/gfmodules-mcsd-consumer-private"
readme = "README.md"
packages = [{ include = "app" }]

[tool.poetry.dependencies]
python = "^3.11"
uvicorn = "^0.34.1"
fastapi = "^0.115.12"
mypy = "^1.15.0"
pydantic-settings = "^2.8.1"
inject = "^5.2.0"
sqlalchemy = "^2.0.40"
psycopg = { extras = ["binary", "pool"], version = "^3.2.6" }
requests = "^2.32.0"
fhir-resources = "^8.0.0"
opentelemetry-sdk = "^1.29.0"
opentelemetry-exporter-otlp-proto-grpc = "^1.29.0"
opentelemetry-instrumentation = "^0.50b0"
opentelemetry-instrumentation-fastapi = "^0.50b0"
opentelemetry-instrumentation-requests = "^0.50b0"
statsd = "^4.0.1"
yarl = "^1.19.0"
requests-aws4auth = "^1.3.1"
boto3 = "^1.37.33"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
pytest-cov = "^6.1.1"
httpx = "^0.28.1"
ruff = "^0.11.5"
safety = "^3.3.0"
codespell = "^2.2.6"
types-requests = "^2.32"
faker = "^37.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
cache-dir = "~/.cache/ruff"
include = ["pyproject.toml", "app/*.py", "tests/*.py"]

[tool.mypy]
files = "app,tests"
python_version = "3.11"
strict = true
cache_dir = "~/.cache/mypy"
ignore_missing_imports = true

[tool.pytest.ini_options]
cache_dir = "~/.cache/pytest"
testpaths = ["tests"]
