server:
  port: 8443
  ssl:
    enabled: true
    protocol: TLS
    key-store: /certificates/server-keystore.p12
    key-store-password: secret
    key-store-type: PKCS12
    client-auth: need
    trust-store: /certificates/truststore.p12
    trust-store-password: secret
    trust-store-type: PKCS12

spring:
  datasource:
    url: 'jdbc:postgresql://postgres:5432/hapi_update_client'
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect
      hibernate.search.enabled: true

hapi:
  fhir:
    tester:
      home:
        id: home
        name: hapi2 Tester
        server_address: 'https://localhost:8443/fhir'
        refuse_to_fetch_third_party_urls: false
        fhir_version: R4
    allow_multiple_delete: true
    allow_expunge: true
    delete_expunge_enabled: true
    allow_cascading_deletes: true
