name: Integration tests
on:
  push:
    branches:
      - main

jobs:
  trigger-ci:
    runs-on: ubuntu-24.04
    steps:
      - name: Trigger CI suite
        uses: minvws/nl-irealisatie-generic-pipelines/.github/actions/gfmodules-trigger-ci@main
        with:
          orac_htpasswd: '${{ secrets.ORAC_HTPASSWD }}'
          endpoint_url: '${{ secrets.ORAC_ENDPOINT }}'
