name: Integration tests
on:
  push:
    branches:
      - main

jobs:
  trigger-ci:
    runs-on: ubuntu-24.04
    steps:
      - name: Trigger CI suite
        uses: minvws/gfmodules-action-trigger-ci@v1
        with:
          orac_htpasswd: '${{ secrets.ORAC_HTPASSWD }}'
          endpoint_url: '${{ secrets.ORAC_ENDPOINT }}'
